#If your server runs in paper, you can use components

#Should the message be sorted randomly?
random-message: false
#Use minimessage format instead of legacy color codes? ---REQUIRES PAPER---
#If you do not want to use components, you can set this to false and then use the "&" codes instead.
component: true
#time between each message
time: 60
messages: ["<gradient:#47e7ff:#2fab24>[Surf Announcements]</gradient> <red>Hello %player%. This message require component = true.</red>", "&b[Surf Announcements] Hello %player%. &6This message requires component = false."]

# If you want to disable the messages, leave "messages" with only []
# messages: []